name: SAM build & validate
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sam-build-validate:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v4
      - run: npm ci
      - run: sam build
      - run: sam validate